{"date":"Sat Apr 09 2022 03:21:29 GMT+0200 (Eastern European Standard Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: Cannot populate path `bugId` because it is not in your schema. Set the `strictPopulate` option to false to override.\nMongooseError: Cannot populate path `bugId` because it is not in your schema. Set the `strictPopulate` option to false to override.\n    at getModelsMapForPopulate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:47:12)\n    at populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4502:21)\n    at _populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4462:5)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4440:5\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:10:12)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Function.Model.populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4438:23)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\query.js:2247:19\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\query\\completeMany.js:36:32\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)","os":{"loadavg":[0,0,0],"uptime":8176674},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\node apps\\bug-tracker-api\\index.js"],"cwd":"E:\\projects\\node apps\\bug-tracker-api","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18345251,"external":20006915,"heapTotal":24612864,"heapUsed":22926936,"rss":54673408},"pid":2144,"uid":null,"version":"v14.18.0"},"stack":"MongooseError: Cannot populate path `bugId` because it is not in your schema. Set the `strictPopulate` option to false to override.\n    at getModelsMapForPopulate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:47:12)\n    at populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4502:21)\n    at _populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4462:5)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4440:5\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:10:12)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Function.Model.populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4438:23)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\query.js:2247:19\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\query\\completeMany.js:36:32\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)","trace":[{"column":12,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js","function":"getModelsMapForPopulate","line":47,"method":null,"native":false},{"column":21,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js","function":"populate","line":4502,"method":null,"native":false},{"column":5,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js","function":"_populate","line":4462,"method":null,"native":false},{"column":5,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js","function":null,"line":4440,"method":null,"native":false},{"column":12,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js","function":"promiseOrCallback","line":10,"method":null,"native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":"Mongoose._promiseOrCallback","line":1174,"method":"_promiseOrCallback","native":false},{"column":23,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js","function":"Function.Model.populate","line":4438,"method":"populate","native":false},{"column":19,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\query.js","function":null,"line":2247,"method":null,"native":false},{"column":32,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\query\\completeMany.js","function":null,"line":36,"method":null,"native":false},{"column":11,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":77,"method":null,"native":false}]}
{"date":"Sat Apr 09 2022 03:21:55 GMT+0200 (Eastern European Standard Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: Cannot populate path `bugId` because it is not in your schema. Set the `strictPopulate` option to false to override.\nMongooseError: Cannot populate path `bugId` because it is not in your schema. Set the `strictPopulate` option to false to override.\n    at getModelsMapForPopulate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:47:12)\n    at populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4502:21)\n    at _populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4462:5)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4440:5\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:10:12)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Function.Model.populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4438:23)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\query.js:2247:19\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\query\\completeMany.js:36:32\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)","os":{"loadavg":[0,0,0],"uptime":8176700},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\node apps\\bug-tracker-api\\index.js"],"cwd":"E:\\projects\\node apps\\bug-tracker-api","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18419857,"external":20083483,"heapTotal":58167296,"heapUsed":25813744,"rss":69386240},"pid":11616,"uid":null,"version":"v14.18.0"},"stack":"MongooseError: Cannot populate path `bugId` because it is not in your schema. Set the `strictPopulate` option to false to override.\n    at getModelsMapForPopulate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:47:12)\n    at populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4502:21)\n    at _populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4462:5)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4440:5\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:10:12)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Function.Model.populate (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js:4438:23)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\query.js:2247:19\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\query\\completeMany.js:36:32\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)","trace":[{"column":12,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js","function":"getModelsMapForPopulate","line":47,"method":null,"native":false},{"column":21,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js","function":"populate","line":4502,"method":null,"native":false},{"column":5,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js","function":"_populate","line":4462,"method":null,"native":false},{"column":5,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js","function":null,"line":4440,"method":null,"native":false},{"column":12,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js","function":"promiseOrCallback","line":10,"method":null,"native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":"Mongoose._promiseOrCallback","line":1174,"method":"_promiseOrCallback","native":false},{"column":23,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\model.js","function":"Function.Model.populate","line":4438,"method":"populate","native":false},{"column":19,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\query.js","function":null,"line":2247,"method":null,"native":false},{"column":32,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\query\\completeMany.js","function":null,"line":36,"method":null,"native":false},{"column":11,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":77,"method":null,"native":false}]}
{"date":"Tue Apr 12 2022 01:39:16 GMT+0200 (Eastern European Standard Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: Cannot call abortTransaction twice\nMongoTransactionError: Cannot call abortTransaction twice\n    at endTransaction (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\sessions.js:430:22)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\sessions.js:259:58\n    at maybePromise (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\utils.js:496:5)\n    at ClientSession.abortTransaction (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\sessions.js:259:41)\n    at E:\\projects\\node apps\\bug-tracker-api\\routes\\projects.js:96:19\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","os":{"loadavg":[0,0,0],"uptime":8429741},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\node apps\\bug-tracker-api\\index.js"],"cwd":"E:\\projects\\node apps\\bug-tracker-api","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18325405,"external":19997819,"heapTotal":24612864,"heapUsed":22318664,"rss":54513664},"pid":8756,"uid":null,"version":"v14.18.0"},"stack":"MongoTransactionError: Cannot call abortTransaction twice\n    at endTransaction (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\sessions.js:430:22)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\sessions.js:259:58\n    at maybePromise (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\utils.js:496:5)\n    at ClientSession.abortTransaction (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\sessions.js:259:41)\n    at E:\\projects\\node apps\\bug-tracker-api\\routes\\projects.js:96:19\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","trace":[{"column":22,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\sessions.js","function":"endTransaction","line":430,"method":null,"native":false},{"column":58,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\sessions.js","function":null,"line":259,"method":null,"native":false},{"column":5,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\utils.js","function":"maybePromise","line":496,"method":null,"native":false},{"column":41,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongodb\\lib\\sessions.js","function":"ClientSession.abortTransaction","line":259,"method":"abortTransaction","native":false},{"column":19,"file":"E:\\projects\\node apps\\bug-tracker-api\\routes\\projects.js","function":null,"line":96,"method":null,"native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
{"date":"Sun Apr 17 2022 15:43:44 GMT+0200 (Eastern European Standard Time)","error":{"code":"ECONNREFUSED","hostname":"_mongodb._tcp.cluster0.0t9tg.mongodb.net","syscall":"querySrv"},"exception":true,"level":"error","message":"unhandledRejection: querySrv ECONNREFUSED _mongodb._tcp.cluster0.0t9tg.mongodb.net\nError: querySrv ECONNREFUSED _mongodb._tcp.cluster0.0t9tg.mongodb.net\n    at QueryReqWrap.onresolve [as oncomplete] (dns.js:210:19)","os":{"loadavg":[0,0,0],"uptime":400056},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\node apps\\bug-tracker-api\\index.js"],"cwd":"E:\\projects\\node apps\\bug-tracker-api","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18280518,"external":20683613,"heapTotal":56594432,"heapUsed":19925600,"rss":65167360},"pid":5420,"uid":null,"version":"v14.18.0"},"stack":"Error: querySrv ECONNREFUSED _mongodb._tcp.cluster0.0t9tg.mongodb.net\n    at QueryReqWrap.onresolve [as oncomplete] (dns.js:210:19)","trace":[{"column":19,"file":"dns.js","function":"QueryReqWrap.onresolve [as oncomplete]","line":210,"method":"onresolve [as oncomplete]","native":false}]}
{"date":"Sun Apr 17 2022 15:44:36 GMT+0200 (Eastern European Standard Time)","error":{"code":"ECONNREFUSED","hostname":"_mongodb._tcp.cluster0.0t9tg.mongodb.net","syscall":"querySrv"},"exception":true,"level":"error","message":"unhandledRejection: querySrv ECONNREFUSED _mongodb._tcp.cluster0.0t9tg.mongodb.net\nError: querySrv ECONNREFUSED _mongodb._tcp.cluster0.0t9tg.mongodb.net\n    at QueryReqWrap.onresolve [as oncomplete] (dns.js:210:19)","os":{"loadavg":[0,0,0],"uptime":400108},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\node apps\\bug-tracker-api\\index.js"],"cwd":"E:\\projects\\node apps\\bug-tracker-api","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18280518,"external":20700277,"heapTotal":56594432,"heapUsed":19918168,"rss":65040384},"pid":6356,"uid":null,"version":"v14.18.0"},"stack":"Error: querySrv ECONNREFUSED _mongodb._tcp.cluster0.0t9tg.mongodb.net\n    at QueryReqWrap.onresolve [as oncomplete] (dns.js:210:19)","trace":[{"column":19,"file":"dns.js","function":"QueryReqWrap.onresolve [as oncomplete]","line":210,"method":"onresolve [as oncomplete]","native":false}]}
{"date":"Sun Apr 17 2022 16:18:26 GMT+0200 (Eastern European Standard Time)","error":{"message":"connect ECONNREFUSED 127.0.0.1:27017","reason":{"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"servers":{},"stale":false,"type":"Unknown"}},"exception":true,"level":"error","message":"unhandledRejection: connect ECONNREFUSED 127.0.0.1:27017\nMongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\connection.js:807:32)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:340:10\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Mongoose.connect (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:339:20)\n    at Object.<anonymous> (E:\\projects\\node apps\\bug-tracker-api\\index.js:91:4)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","os":{"loadavg":[0,0,0],"uptime":402140},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\node apps\\bug-tracker-api\\index.js"],"cwd":"E:\\projects\\node apps\\bug-tracker-api","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18280530,"external":19833720,"heapTotal":23040000,"heapUsed":20885640,"rss":51785728},"pid":1260,"uid":null,"version":"v14.18.0"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\connection.js:807:32)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:340:10\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Mongoose.connect (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:339:20)\n    at Object.<anonymous> (E:\\projects\\node apps\\bug-tracker-api\\index.js:91:4)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","trace":[{"column":32,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\connection.js","function":"NativeConnection.Connection.openUri","line":807,"method":"openUri","native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":null,"line":340,"method":null,"native":false},{"column":5,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js","function":null,"line":32,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js","function":"promiseOrCallback","line":31,"method":null,"native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":"Mongoose._promiseOrCallback","line":1174,"method":"_promiseOrCallback","native":false},{"column":20,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":"Mongoose.connect","line":339,"method":"connect","native":false},{"column":4,"file":"E:\\projects\\node apps\\bug-tracker-api\\index.js","function":null,"line":91,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1085,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1114,"method":".js","native":false}]}
{"date":"Sun Apr 17 2022 16:20:05 GMT+0200 (Eastern European Standard Time)","error":{"message":"Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/","reason":{"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"servers":{},"setName":"atlas-fmtdez-shard-0","stale":false,"type":"ReplicaSetNoPrimary"}},"exception":true,"level":"error","message":"unhandledRejection: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/\nMongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/\n    at NativeConnection.Connection.openUri (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\connection.js:807:32)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:340:10\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Mongoose.connect (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:339:20)\n    at Object.<anonymous> (E:\\projects\\node apps\\bug-tracker-api\\index.js:92:4)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","os":{"loadavg":[0,0,0],"uptime":402236},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\node apps\\bug-tracker-api\\index.js"],"cwd":"E:\\projects\\node apps\\bug-tracker-api","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18292620,"external":19845810,"heapTotal":21991424,"heapUsed":20651872,"rss":51646464},"pid":3172,"uid":null,"version":"v14.18.0"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/\n    at NativeConnection.Connection.openUri (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\connection.js:807:32)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:340:10\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Mongoose.connect (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:339:20)\n    at Object.<anonymous> (E:\\projects\\node apps\\bug-tracker-api\\index.js:92:4)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","trace":[{"column":32,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\connection.js","function":"NativeConnection.Connection.openUri","line":807,"method":"openUri","native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":null,"line":340,"method":null,"native":false},{"column":5,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js","function":null,"line":32,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js","function":"promiseOrCallback","line":31,"method":null,"native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":"Mongoose._promiseOrCallback","line":1174,"method":"_promiseOrCallback","native":false},{"column":20,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":"Mongoose.connect","line":339,"method":"connect","native":false},{"column":4,"file":"E:\\projects\\node apps\\bug-tracker-api\\index.js","function":null,"line":92,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1085,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1114,"method":".js","native":false}]}
{"date":"Sun Apr 17 2022 16:21:55 GMT+0200 (Eastern European Standard Time)","error":{"message":"Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/","reason":{"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"servers":{},"setName":"atlas-fmtdez-shard-0","stale":false,"type":"ReplicaSetNoPrimary"}},"exception":true,"level":"error","message":"unhandledRejection: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/\nMongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/\n    at NativeConnection.Connection.openUri (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\connection.js:807:32)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:340:10\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Mongoose.connect (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:339:20)\n    at Object.<anonymous> (E:\\projects\\node apps\\bug-tracker-api\\index.js:92:4)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","os":{"loadavg":[0,0,0],"uptime":402347},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","E:\\projects\\node apps\\bug-tracker-api\\index.js"],"cwd":"E:\\projects\\node apps\\bug-tracker-api","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18280530,"external":19833720,"heapTotal":21991424,"heapUsed":20442048,"rss":51343360},"pid":9736,"uid":null,"version":"v14.18.0"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/\n    at NativeConnection.Connection.openUri (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\connection.js:807:32)\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:340:10\n    at E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:1174:10)\n    at Mongoose.connect (E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js:339:20)\n    at Object.<anonymous> (E:\\projects\\node apps\\bug-tracker-api\\index.js:92:4)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","trace":[{"column":32,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\connection.js","function":"NativeConnection.Connection.openUri","line":807,"method":"openUri","native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":null,"line":340,"method":null,"native":false},{"column":5,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js","function":null,"line":32,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js","function":"promiseOrCallback","line":31,"method":null,"native":false},{"column":10,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":"Mongoose._promiseOrCallback","line":1174,"method":"_promiseOrCallback","native":false},{"column":20,"file":"E:\\projects\\node apps\\bug-tracker-api\\node_modules\\mongoose\\lib\\index.js","function":"Mongoose.connect","line":339,"method":"connect","native":false},{"column":4,"file":"E:\\projects\\node apps\\bug-tracker-api\\index.js","function":null,"line":92,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1085,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1114,"method":".js","native":false}]}
